# rename to config.yml
jira:
  username: "xxx@xxxxx.com.br"
  accessToken: "xxxxxxxxxxxxxxx"
  hostname: "https://xxxxxxxx.atlassian.net"
  customFieldStartEstimateDate: customfield_999999
  cacheExpiresSeconds: 600
  status:
    executing:
      - IN PROGRESS
    stopped:
      - BLOCKED
      - READY FOR CODE REVIEW
    done:
      - DEPLOYED
server:
  port: 80
  method: http
dayoffs:
  - "2022-10-12"